PCA-011(Frequently Asked Questions)
Qoosim/practicode-frontend pull request #4
Opened 2023-10-23 14:13 UTC by joseph0x

in this PR, I was able to do the following: 
-created frequently asked questions 
-the link to my ticket https://trello.com/c/wr914kJp/11-pca-011-design-and-develop-responsive-faq-2

2023-10-29 16:17 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @joseph0x, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct . :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


Cheers and Happy coding!👏👏👏

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/FAQ.css
> +  background: url(images/bgimage.png);
- [ ] The path to this image is not correct. It should be like this :point_down: 

```
   background: url(../../images/bgimage.png);
```

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/FAQ.css
> +  background: url(images/newvector.png);
- [ ] Samething with this too. Kindly fix it.

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/Nav.js
> +}
- [ ] Great job so far. However, there're few things to work on here for your design to match with the figma design. Let's try to create this section with padding left and right to match figma design

### Your design

![your-header-part](https://github.com/Qoosim/practicode-frontend/assets/26597432/38f5777c-e05c-4b92-8be4-60929dee8457)


### Figma design

![figma-header-part](https://github.com/Qoosim/practicode-frontend/assets/26597432/38ba853f-aaf7-40ac-9235-8ddd60c0ec64)

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/header.js
> +        <h3 className="black">Get Every General Answers From Here</h3>
- [ ] Kindly follow the layout on the figma design to style this heading. You might need to check the font-size use on the original design.

### Your Design
![your-gen-ans](https://github.com/Qoosim/practicode-frontend/assets/26597432/995b63a0-46c0-486d-8ab7-956acd42bcd5)

### Figma Design
![figma-gen-ans](https://github.com/Qoosim/practicode-frontend/assets/26597432/40904c6e-f517-44d1-aaf5-6fe22f1da607)

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/header.js
> +          </a>
- [ ] The border-radius given to this element does not tally with how it appears on the figma design. Kindly check and fix it.

### Your Design
![your-btn-shape](https://github.com/Qoosim/practicode-frontend/assets/26597432/9890b3eb-1090-4291-9435-58a9339b0cb6)

### Figma Design
![figma-btn-shape](https://github.com/Qoosim/practicode-frontend/assets/26597432/d62397ef-a1ef-43ce-97cc-5dcb0ed6aa67)

2023-10-29 16:17 UTC, Qoosim commented on src/components/FAQs/Question.js
> +        <hr />
- [ ] Kindly check how this appears on the figma design and fix those areas I pointed out. 
- [ ] Also, check out the thickness and color opacity of the liine

### Your Desgin
![your-line-size](https://github.com/Qoosim/practicode-frontend/assets/26597432/547dba99-b95f-4fc5-84f9-edef63339e22)

### Figma Design
![figma-line-size](https://github.com/Qoosim/practicode-frontend/assets/26597432/62a610c9-c1a4-4375-8c64-c6dfbe10ccf5)

2023-10-30 07:41 UTC, joseph0x commented
<img width="919" alt="changesmadePCA-011(#3)" src="https://github.com/Qoosim/practicode-frontend/assets/109046986/832b7a7f-ba9b-4208-bd42-a40a8206202e">

<img width="923" alt="changesmadePCA-011(#2)" src="https://github.com/Qoosim/practicode-frontend/assets/109046986/aa1a9b39-d5e0-4879-8fa7-adc180cd6741">

how about now sir?

2023-10-30 07:56 UTC, joseph0x reviewed
corrections made

2023-10-30 07:57 UTC, merged